name: step02_condition
on: workflow_dispatch
jobs:
  build:
    if: github.repository == 'bbmini96/github-action-test'
    runs-on: ubuntu-latest
    steps:
    - name: Print Result
      run: |
        echo "Run Build on bbmini96/github-action-test"
